type: array
items:
  oneOf:
    - type: string
    - type: object
      required:
        - source
      properties:
        source:
          type: string
        target:
          type: string
        uid:
          type: string
        gid:
          type: string
        mode:
          type: number
      container_name:
        type: string
